---
- name: Provision VPC For OpenShift 4
  hosts: localhost
  vars_files:
    - vars/us-east-1.yaml
  roles:
  - role: openshift-vpc
    vars:
      region: "us-east-1"
      prefix: "ckeller-acm-openshift-vpn"