- name: Query VPC ID for VPC {{ prefix }}
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ prefix }}"
    region: "{{ region }}"
  register: vpc_results

- name: Debug vpc_results
  ansible.builtin.debug:
    var: vpc_results
    verbosity: 2
      
- name: Query NAT Gateways for VPC {{ prefix }}
  amazon.aws.ec2_vpc_nat_gateway_info:
    filters:
      vpc-id: "{{ vpc_results.vpcs[0].vpc_id }}"
  register: ngw_results

- name: Debug ngw_results
  ansible.builtin.debug:
    var: ngw_results
    verbosity: 2

- name: Delete VPC NAT Gateways for VPC {{ prefix }}
  amazon.aws.ec2_vpc_nat_gateway:
    nat_gateway_id: "{{ item.nat_gateway_id }}"
    release_eip: true
    state: absent
    wait: true
  with_items:
    - "{{ ngw_results.result }}"

- name: Delete VPC Internet Gateway for VPC {{ prefix }}
  amazon.aws.ec2_vpc_igw:
    region: "{{ region }}"
    state: absent
    vpc_id: "{{ vpc_results.vpcs[0].vpc_id }}"

- name: Query S3 Endpoint for VPC {{ prefix }}
  amazon.aws.ec2_vpc_endpoint_info:
    filters:
      vpc-id: "{{ vpc_results.vpcs[0].vpc_id  }}"
    query: endpoints
    region: "{{ region }}"
  register: endpoint_results

- name: Debug endpoint_results
  ansible.builtin.debug:
    var: endpoint_results
    verbosity: 2

- name: Delete Endpoint for VPC {{ prefix }}
  amazon.aws.ec2_vpc_endpoint:
    region: "{{ region }}"
    state: absent
    vpc_endpoint_id: "{{ endpoint_results.vpc_endpoints[0].vpc_endpoint_id }}"
    vpc_id: "{{ vpc_results.vpcs[0].vpc_id  }}"
    wait: yes
  when: endpoint_results.vpc_endpoints[0].vpc_endpoint_id is defined

- name: Query RTBs for VPC {{ prefix }}
  community.aws.ec2_vpc_route_table_info:
    filters:
      vpc-id: "{{ vpc_results.vpcs[0].vpc_id }}"
    region: "{{ region }}"
  register: rtb_results

- name: Debug rtb_results
  ansible.builtin.debug:
    var: rtb_results
    verbosity: 2

- name: Delete RTBs for VPC {{ prefix }}
  community.aws.ec2_vpc_route_table:
    lookup: id
    region: "{{ region }}"
    route_table_id: "{{ item.id }}"
    state: absent
    vpc_id: "{{ vpc_results.vpcs[0].vpc_id }}"
  loop: "{{ rtb_results.route_tables }}"
  when: 
    - (item.associations[0].main is not defined) or ((item.associations[0].main is defined) and (item.associations[0].main != true))

- name: Query Subnets for VPC {{ prefix }}
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc_results.vpcs[0].vpc_id }}"
    region: "{{ region }}"
  register: subnet_results

- name: Debug subnet_results
  ansible.builtin.debug:
    var: subnet_results
    verbosity: 2

- name: Delete Subnets for VPC {{ prefix }}
  amazon.aws.ec2_vpc_subnet:
    cidr: "{{ item.cidr_block }}"
    state: absent
    vpc_id: "{{ vpc_results.vpcs[0].vpc_id }}"
  with_items:
    - "{{ subnet_results.subnets }}"

- name: Delete VPC {{ prefix }}
  amazon.aws.ec2_vpc_net:
    cidr_block: "{{ cidr_block }}"
    name: "{{ prefix }}"
    region: "{{ region }}"
    state: absent
