- name: Include Region Specific Vars
  ansible.builtin.include_vars:
    file: us-east-1.yaml
  when:
    - region == "us-east-1"

- name: Create VPC {{ prefix }}
  amazon.aws.ec2_vpc_net:
    region: "{{ region }}"
    cidr_block: "{{ cidr_block }}"
    dns_hostnames: yes
    dns_support: yes
    name: "{{ prefix }}"
    state: present
  delay: 10
  register: vpc_results
  retries: 10
  until:
    - (vpc_results.failed is not defined) or (vpc_results.failed == false)

- name: Debug vpc_results
  ansible.builtin.debug:
    var: vpc_results
    verbosity: 1

- name: Create Internet Gateway for VPC {{ prefix }} Public Subnets
  amazon.aws.ec2_vpc_igw:
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ prefix }}-igw"
    vpc_id: "{{ vpc_results.vpc.id }}"
  delay: 10
  register: igw_results
  retries: 10
  until:
    - (igw_results.failed is not defined) or (igw_results.failed == false)

- name: Debug igw_results
  ansible.builtin.debug:
    var: igw_results
    verbosity: 1

- name: Create Subnets for VPC {{ prefix }}
  amazon.aws.ec2_vpc_subnet:
    az: "{{ item.az }}"
    cidr: "{{ item.cidr }}"
    region: "{{ item.region }}"
    state: present
    tags:
      Name: "{{ item.name }}"
    vpc_id: "{{ vpc_results.vpc.id }}"
  delay: 10
  loop: "{{ subnets }}"
  register: subnet_results
  retries: 10
  until:
    - (subnet_results.failed is not defined) or (subnet_results.failed == false)

- name: Debug subnet_results
  ansible.builtin.debug:
    var: subnet_results
    verbosity: 1

- name: Query Private Subnet Info for VPC {{ prefix }}
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc_results.vpc.id }}"
      "tag:Name": "{{ item.name }}"
    region: "{{ region }}"
  delay: 10
  loop: "{{ subnets }}"
  register: private_subnet_results
  retries: 10
  until:
    - (private_subnet_results.failed is not defined) or (private_subnet_results.failed == false)
  when:
    - item.type == "private"

- name: Debug private_subnet_results
  ansible.builtin.debug:
    var: private_subnet_results
    verbosity: 1

- name: Define List of Private Subnet IDs + Name for VPC {{ prefix }}
  ansible.builtin.set_fact:
    private_subnet_info: >-
      {{
        private_subnet_info | default([]) +
        [
          {
            'name': item.subnets[0].tags.Name,
            'id': item.subnets[0].subnet_id
          }
        ]
      }}
  loop: "{{ private_subnet_results.results }}"
  when:
    - item.skipped is not defined

- name: Debug private_subnet_info
  debug:
    var: private_subnet_info
    verbosity: 1

- name: Define List of Private Subnet Names for VPC {{ prefix }}
  set_fact:
    private_subnet_list: >-
      {{
        private_subnet_list | default([]) +
        [
          item.subnets[0].tags.Name
        ]
      }}
  loop: "{{ private_subnet_results.results }}"
  when:
    - item.skipped is not defined

- name: Debug private_subnet_list
  debug:
    var: private_subnet_list
    verbosity: 1

- name: Query Public Subnet Info for VPC {{ prefix }}
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc_results.vpc.id }}"
      "tag:Name": "{{ item.name }}"
    region: "{{ region }}"
  delay: 10
  loop: "{{ subnets }}"
  register: public_subnet_results
  retries: 10
  until:
    - (public_subnet_results.failed is not defined) or (public_subnet_results.failed == false)
  when:
    - item.type == "public"

- name: Debug public_subnet_results
  ansible.builtin.debug:
    var: public_subnet_results
    verbosity: 1

- name: Define List of Public Subnet IDs + Name for VPC {{ prefix }}
  ansible.builtin.set_fact:
    public_subnet_info: >-
      {{
        public_subnet_info | default([]) +
        [
          {
            'name': item.subnets[0].tags.Name,
            'id': item.subnets[0].subnet_id
          }
        ]
      }}
  loop: "{{ public_subnet_results.results }}"
  when:
    - item.skipped is not defined

- name: Debug public_subnet_info
  ansible.builtin.debug:
    var: public_subnet_info
    verbosity: 1

- name: Define List of Public Subnet Names for VPC {{ prefix }}
  ansible.builtin.set_fact:
    public_subnet_list: >-
      {{
        public_subnet_list | default([]) +
        [
          item.subnets[0].tags.Name
        ]
      }}
  loop: "{{ public_subnet_results.results }}"
  when:
    - item.skipped is not defined

- name: Debug public_subnet_list
  ansible.builtin.debug:
    var: public_subnet_list
    verbosity: 1

- name: Define List of Public Subnet IDs for VPC {{ prefix }}
  ansible.builtin.set_fact:
    public_subnet_ids: "{{ public_subnet_ids | default([]) + [item.subnets[0].subnet_id] }}"
  loop: "{{ public_subnet_results.results }}"
  when:
    - item.skipped is not defined

- name: Debug public_subnet_ids
  ansible.builtin.debug:
    var: public_subnet_ids
    verbosity: 1

- name: Query NAT Gateway EIPs for VPC {{ prefix }} Public Subnets
  community.aws.ec2_eip_info:
    filters:
      "tag:Name": "{{ item.name }}-ngw-eip"
  loop: "{{ public_subnet_info }}"
  register: eip_results

- name: Debug eip_results
  ansible.builtin.debug:
    var: eip_results
    verbosity: 1

- name: Define List of Existing EIPs for VPC {{ prefix }} Public Subnets
  ansible.builtin.set_fact:
    existing_eips: >-
      {{
        existing_eips | default([]) +
        [
          item.addresses[0].tags.Name | regex_replace("-ngw-eip")
        ]
      }}
  loop: "{{ eip_results.results }}"
  when:
    - item.addresses[0] is defined

- name: Debug existing_eips
  ansible.builtin.debug:
    var: existing_eips
    verbosity: 1

- name: Create NAT Gateway EIPs for VPC {{ prefix }} Public Subnets
  community.aws.ec2_eip:
    in_vpc: yes
    region: "{{ region }}"
    state: present
  loop: "{{ public_subnet_list }}"
  register: eip_create_results
  when:
    - (existing_eips is not defined) or (item not in existing_eips)

- name: Debug eip_create_results
  ansible.builtin.debug:
    var: eip_create_results
    verbosity: 1

- name: Tag NAT Gateway EIPs for VPC {{ prefix }} Public Subnets
  amazon.aws.ec2_tag:
    region: "{{ region }}"
    resource: "{{ item.allocation_id }}"
    state: present
    tags:
      Name: "{{ item.item }}-ngw-eip"
  loop: "{{ eip_create_results.results }}"
  when:
    - item.skipped is not defined

- name: Query NAT Gateway EIPs for VPC {{ prefix }} Public Subnets
  community.aws.ec2_eip_info:
    filters:
      "tag:Name": "{{ item.name }}-ngw-eip"
  loop: "{{ public_subnet_info }}"
  register: eip_results

- name: Debug eip_results
  ansible.builtin.debug:
    var: eip_results
    verbosity: 1

- name: Create NAT Gateways for VPC {{ prefix }} Public Subnets
  amazon.aws.ec2_vpc_nat_gateway:
    allocation_id: "{{ item.0.addresses[0].allocation_id }}"
    client_token: "{{ ngw_client_token }}"
    if_exist_do_not_create: true
    region: "{{ region }}"
    state: present
    subnet_id: "{{ item.1.id }}"
    tags:
      Name: "{{ item.1.name }}-ngw"
  delay: 10
  loop: "{{ eip_results.results | zip(public_subnet_info) | list }}"
  register: ngw_results
  retries: 10
  until:
    - (ngw_results.failed is not defined) or (ngw_results.failed == false)

- name: Debug ngw_results
  ansible.builtin.debug:
    var: ngw_results
    verbosity: 1

- name: Create RTBs for VPC {{ prefix }} Private Subnets
  community.aws.ec2_vpc_route_table:
    region: "{{ region }}"
    routes:
      - dest: 0.0.0.0/0
        nat_gateway_id: "{{ item.1.nat_gateway_id }}"
    state: present
    subnets:
      - "{{ item.0.id }}"
    tags:
      Name: "{{ item.0.name }}-rtb"
    vpc_id: "{{ vpc_results.vpc.id }}"
  loop: "{{ private_subnet_info | zip(ngw_results.results) | list }}"
  register: private_rtb_results

- name: Debug private_rtb_results
  ansible.builtin.debug:
    var: private_rtb_results
    verbosity: 1

- name: Create RTB for VPC {{ prefix }} Public Subnets
  community.aws.ec2_vpc_route_table:
    purge_routes: false
    region: "{{ region }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_results.gateway_id }}"
    state: present
    subnets: "{{ public_subnet_ids }}"
    tags:
      Name: "{{ prefix }}-public-rtb"
    vpc_id: "{{ vpc_results.vpc.id }}"
  register: public_rtb_results

- name: Debug public_rtb_results
  ansible.builtin.debug:
    var: public_rtb_results
    verbosity: 1
    
- name: Query RTBs For VPC {{ prefix }} Private Subnets
  community.aws.ec2_vpc_route_table_info:
    filters:
      association.subnet-id: "{{ item.id }}"
    region: "{{ region }}"
  loop: "{{ private_subnet_info }}"
  register: private_rtb_results

- name: Debug private_rtb_results
  ansible.builtin.debug:
    var: private_rtb_results
    verbosity: 1

- name: Add List of Private Route Table IDs for VPC {{ prefix }}
  ansible.builtin.set_fact:
    all_rtb_ids: "{{ all_rtb_ids | default([]) + [item.route_tables[0].id] }}"
  loop: "{{ private_rtb_results.results }}"

- name: Add Public Route Table ID for VPC {{ prefix }}
  ansible.builtin.set_fact:
    all_rtb_ids: "{{ all_rtb_ids + [public_rtb_results.route_table.id] }}"

- name: Debug all_rtb_ids
  ansible.builtin.debug:
    var: all_rtb_ids
    verbosity: 1

- name: Create S3 Endpoint for VPC {{ prefix }}
  amazon.aws.ec2_vpc_endpoint:
    region: "{{ region }}"
    route_table_ids: "{{ all_rtb_ids }}"
    service: "{{ s3_endpoint }}"
    state: present
    vpc_id: "{{ vpc_results.vpc.id }}"
  delay: 10
  register: endpoint_results
  retries: 10

- name: Debug endpoint_results
  ansible.builtin.debug:
    var: endpoint_results
    verbosity: 1

- name: Tag S3 Endpoint for VPC {{ prefix }}
  amazon.aws.ec2_tag:
    region: "{{ region }}"
    resource: "{{ endpoint_results.result.vpc_endpoint_id }}"
    state: present
    tags:
      Name: "{{ prefix }}-s3-endpoint"
